name: Node.js Test and Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd backend  # Change directory to backend folder
          npm install  # Install dependencies
          
      - name: Build Application
        run: |
          cd backend  # Change directory to backend folder
          npm run build  # Build application
